fetching file from server
HANICA-DWA/sep2021-project-opossum pull request #124
Opened 2021-12-18 10:07 UTC by RubenEppink

resolve #111

2021-12-18 19:01 UTC, RubenEppink commented
moet wss nog ff integratie tests schrijven

2021-12-20 08:44 UTC, ilivss requested changes
:ok_hand:

2021-12-20 08:44 UTC, ilivss commented on wcag-tool/backend/src/routers/snapshot.routes.js
> +const { getUpload, mongoose, getBucket } = require('../database')
```suggestion
const { getUpload, getBucket } = require('../database')
```

2021-12-20 08:45 UTC, mjqnsen approved these changes

2021-12-20 14:49 UTC, mjqnsen approved these changes

2021-12-20 15:07 UTC, ilivss approved these changes

2021-12-20 15:11 UTC, merged