show snapshots client-side
HANICA-DWA/sep2021-project-opossum pull request #125
Opened 2021-12-18 10:56 UTC by RubenEppink

Aangezien we niet met pagination gaan werken hoeft er ook niks voor de backend gedaan te worden

fix #110 
fix #109

2021-12-18 11:09 UTC, RubenEppink commented
![image](https://user-images.githubusercontent.com/47324044/146638843-9c230c9f-9dc9-4b18-9419-96ca1847249d.png)

2021-12-18 15:35 UTC, RubenEppink commented
Heb nu de bar fixed gemaakt
![image](https://user-images.githubusercontent.com/47324044/146646623-f3d24e70-ed21-4d36-aedf-a8d267c30a89.png)

2021-12-20 08:49 UTC, ilivss approved these changes
Nice

2021-12-20 08:50 UTC, mjqnsen commented
![image](https://user-images.githubusercontent.com/49095667/146739070-53a08d4e-fd5f-4421-8290-fcecd025606b.png)
Tooltips in popup worden nu incorrect weergeven.

2021-12-20 08:52 UTC, mjqnsen requested changes
Het gehele popup menu heeft een scrollbar. Alleen de body van de popup moet scrollable zijn.

Daarnaast klopt het lettertype en de spacings niet met de styling.

2021-12-20 08:54 UTC, mjqnsen commented
![image](https://user-images.githubusercontent.com/49095667/146739614-617bb2e7-49e7-487a-8dc8-400cf0c7b294.png)
![image](https://user-images.githubusercontent.com/49095667/146739640-0313993b-2d79-47b3-9b40-e28fe7cced76.png)
Text styling maar ook waar de tekst staat klopt niet. De tekst is niet verticaal gecentreerd en is hier bold.

2021-12-20 08:55 UTC, mjqnsen commented
Ik zou de open knop toch weg laten. aangezien dat niet bij deze user story hoort. mag lege div zijn als je dat nodig hebt voor css.

2021-12-20 08:57 UTC, ilivss commented
> Ik zou de open knop toch weg laten. aangezien dat niet bij deze user story hoort. mag lege div zijn als je dat nodig hebt voor css.

Vooraf gezien wel idd, maar nu het er toch staan kun je het net zo goed laten haha

2021-12-20 08:58 UTC, mjqnsen commented
truncate text. naam en site moet single line zijn 
![image](https://user-images.githubusercontent.com/49095667/146740268-8bab3235-090b-4e48-a465-70017af0e265.png)

2021-12-20 09:00 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/components/popup/header.jsx
> +    <div className="flex fixed top-0 w-full p-2 px-4 justify-between items-center border rounded-t-lg bg-gray-100 border-gray-300">
deze bar hoeft niet fixed gemaakt te worden zolang je de body div maar scrollable maakt.
```suggestion
    <div className="flex mt-0.5 p-2 px-4 justify-between items-center border rounded-t-lg bg-gray-100 border-gray-300">
```

2021-12-20 09:04 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/components/popup/SnapshotListItem.jsx
> +            <p className="overflowWrap text-sm text-gray-700 font-poppins-semi">
mss zou je het domein kunnen truncate na de base url en een title toevoegen maar de gehele url inc path

2021-12-20 09:06 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/components/popup/snapshotBody.jsx
> +    <div className="mt-12">
hier heb je wss geen mt-12 nodig.

2021-12-20 12:24 UTC, mjqnsen commented
styling update
![image](https://user-images.githubusercontent.com/49095667/146766810-eecbcef7-88a5-449e-be51-6981d9ffc992.png)

2021-12-20 12:29 UTC, mjqnsen approved these changes

2021-12-20 12:46 UTC, merged