Task/103 overdracht
HANICA-DWA/sep2021-project-opossum pull request #133
Opened 2021-12-20 18:07 UTC by RubenEppink

2021-12-21 12:20 UTC, mjqnsen requested changes

2021-12-21 12:20 UTC, mjqnsen commented on README.md
> +## Configuring MongoDB Atlas
mss iets over dat gebruik van een mongodb atlas niet verplicht is maar dus ook een anders soort mongodb kan zijn. zolanghet maar in de vorm van een mongo uri is.

2021-12-21 12:20 UTC, mjqnsen commented on README.md
> +## Deploying to the chrome store
hier zou je nog aan toe kunnen voegen dat de chrome extension eerst gebuild moet worden voordat dit kan. En dat die informatie te vinden is in de readme.md van dat project.

2021-12-21 12:20 UTC, mjqnsen commented on README.md
> +## Project scripts
ik zou deze sectie voor de vorige sectie plaatsen. dat er eerst informatie komt over hoe je de extentie build / developped en daarna pas hoe je de exntesie toevoegd aan je browser.

2021-12-21 12:43 UTC, mjqnsen approved these changes

2021-12-22 10:54 UTC, ilivss approved these changes

2021-12-22 10:54 UTC, ilivss commented on README.md
> +- Install Node.js 16+
LTS

2021-12-22 10:54 UTC, ilivss commented on README.md
> +   MONGO_URI=mongodb+srv://admin:<password>@cluster0.t2xwc.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
```suggestion
   PORT=<port number>
   MONGO_URI=<mongo connection uri>
```

2021-12-22 10:54 UTC, ilivss commented on README.md
> +Make sure the MONGO_URI is on one line, without line breaks. Replace `admin` and `<password>` with your own username and password. Replace `myFirstDatabase` with the corresponding database name you a
```suggestion
> Make sure the MONGO_URI is on one line, without line breaks. Replace `admin` and `<password>` with your own username and password. Replace `myFirstDatabase` with the corresponding database name you are going to use for your development and test database. **WARNING: YOUR TEST AND DEVELOPMENT DATABASES NEED TO HAVE DIFFERENT NAMES.**
```

2021-12-22 10:54 UTC, ilivss commented on README.md
> +# Installation guide
Titel en inhoudsopgave missen

2021-12-22 10:54 UTC, ilivss commented on README.md
> +## Configuring MongoDB Atlas
+ ik zou dit stukje helemaal naar onder verplaatsen, aangezien dit info is voor simpele zielen

2021-12-22 10:54 UTC, ilivss commented on README.md
> +
```suggestion
> Instead of using a local MongoDB instance we strongly recommend using MongoDB Atlas, follow the instructions [here](#configuring-mongodb-atlas)
```

2021-12-22 10:54 UTC, ilivss commented on README.md
> +Installs all dependencies for the backend and frontend. Bundles all the files for the chrome extension.
```suggestion
Installs all dependencies for the backend and frontend. Bundles all the files for the chrome extension. This command also builds the co-dependency`single-file`.
```

2021-12-22 10:54 UTC, ilivss commented on README.md
> +Run all unit integration tests for both front- and backend.
```suggestion
Run all integration tests for the backend.
```

2021-12-22 10:54 UTC, ilivss commented on README.md
> +Before deploying you should make sure you built the project properly. This ensures you have the latest changes and the dist folder is up to date. More about this can be found in the [chrome-extension
Kvind deze alinea beetje verwarren, eerst staat er lees hier, daarna instructies. Leken kunnen hierdoor in de war raken I guess?

2021-12-22 15:38 UTC, ilivss approved these changes

2021-12-22 15:44 UTC, merged