set username in option menu
HANICA-DWA/sep2021-project-opossum pull request #134
Opened 2021-12-21 12:05 UTC by RubenEppink

2021-12-21 12:05 UTC, RubenEppink commented
![image](https://user-images.githubusercontent.com/47324044/146927205-3ea8f0d5-fa03-429c-984f-d258e7fa3a82.png)

2021-12-21 12:06 UTC, RubenEppink commented
![image](https://user-images.githubusercontent.com/47324044/146927234-2707cbe5-4e7a-4a80-8f59-3a6e03f977f1.png)

2021-12-21 12:38 UTC, mjqnsen commented
![image](https://user-images.githubusercontent.com/49095667/146931333-1ba03f71-fb8d-47b3-9735-943191fd21a9.png)

2021-12-21 12:40 UTC, mjqnsen requested changes
Looks good. Er is alleen nog geen feedback wanneer er op de save knop word geklikt.

2021-12-21 13:08 UTC, mjqnsen approved these changes

2021-12-21 13:33 UTC, RubenEppink commented
fix #120

2021-12-22 12:27 UTC, ilivss requested changes
Nice

2021-12-22 14:04 UTC, mjqnsen approved these changes

2021-12-22 15:47 UTC, ilivss approved these changes

2021-12-22 15:48 UTC, merged