open options page
HANICA-DWA/sep2021-project-opossum pull request #135
Opened 2021-12-21 13:32 UTC by RubenEppink

2021-12-21 13:33 UTC, RubenEppink commented
fix #121

2021-12-22 08:45 UTC, mjqnsen requested changes
Ik kan deze nog niet testen zolang de vorige pr er nog niet doorheen is.

2021-12-22 08:45 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/components/popup/header.jsx
> +          className="h-6 w-6 inline text-gray-600 hover:text-gray-800 ml-2 mb-1 cursor-pointer"
```suggestion
          className="h-6 w-6 inline text-gray-600 hover:text-gray-700 ml-2 mb-1 cursor-pointer"
```

2021-12-22 11:10 UTC, ilivss commented
nice!

2021-12-22 12:26 UTC, ilivss approved these changes

2021-12-22 13:12 UTC, mjqnsen approved these changes

2021-12-22 13:13 UTC, merged