label
HANICA-DWA/sep2021-project-opossum pull request #136
Opened 2021-12-21 14:31 UTC by RubenEppink

fix #119 

![image](https://user-images.githubusercontent.com/47324044/146946607-64eec24c-d05c-4908-9512-f6fd32c5650c.png)

2021-12-22 08:56 UTC, mjqnsen requested changes
![image](https://user-images.githubusercontent.com/49095667/147064942-66d135c5-4c6b-4425-83ea-115c664b0b22.png)
Te veel ruimte tussen de annotatie description en de labels.

Er zijn geen labels te zien op de detail page.

2021-12-22 11:13 UTC, ilivss commented on wcag-tool/chrome-extension/src/components/editor/AnnotationListItem.jsx
> +              <LabelList labels={labels} />
Deze zou ik ook laten zien op de AnnotationDetailSlider

2021-12-22 11:13 UTC, ilivss requested changes
Gruwelijk!

2021-12-22 15:57 UTC, ilivss approved these changes

2021-12-23 08:16 UTC, mjqnsen approved these changes

2021-12-23 08:17 UTC, merged