Task/116 axe core snapshot analyse
HANICA-DWA/sep2021-project-opossum pull request #140
Opened 2021-12-22 14:57 UTC by ilivss

Eerst #139 
Closes #116

2021-12-23 08:30 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/components/editor/AnnotationListSlider.jsx
> +                Nu.nl Homepage text is...
werkt truncate nu wel correct met de nieuwe knop?

2021-12-23 08:49 UTC, mjqnsen requested changes
Aantal dingen:
- [ ] Border tussen de dualbutton is iets te dik, maak kleiner door de border left or right van 1 van de buttons weg te halen.
- [ ] Behaviour van de dropdown is apart. Als je klikt moet bijvoorbeeld het menu weg gaan en als je er buiten hovered moet de lijst nog wel open blijven.
- [ ] Als je op de knop in de dropdown klikt moet die weg gaan.
- [ ] Ik mis een loading state. Verander het plusje naar een buffer icoon wanneer de analyse bezig is.
- [ ] Volg wat meer de styling van figma voor dropdowns. bijvoorbeeld dat de kleur van tekst en icoontjes iets meer grijs moet zijn.
![6](https://user-images.githubusercontent.com/49095667/147214940-2c00d065-309d-45b1-8d87-9966e2d1e53c.gif)

2021-12-23 08:49 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/hooks/editor.hooks.js
> +          content: false,
als je geen content gebruikt hoef je het ook niet mee te sturen

2021-12-24 08:35 UTC, mjqnsen commented on wcag-tool/chrome-extension/postinstall.js
> +fs.mkdir(path.join('dist', 'js'), { recursive: true }, () =>
Als je alleen deze file wilt kopieren dan had ik je niet goed begrepen. by bad.
Je kan ook deze file kopieren met de webpack config.

2021-12-24 09:43 UTC, mjqnsen commented
Ik heb een styling en een refactoring gedaan.
Het enige wat nog gedaan moet worden is zorgen dat er een loading state is, door het plus icoon te veranderen in een spinner en beide knoppen disabled te maken. @ilivss

2022-01-05 16:21 UTC, ilivss commented on wcag-tool/chrome-extension/src/hooks/editor.hooks.js
> +          content: false,
![loading-state](https://user-images.githubusercontent.com/6729273/148251745-ac4e0d6a-37bb-4a1c-9836-0c9ba94cc256.gif)
![error-preview](https://user-images.githubusercontent.com/6729273/148251768-73e29071-76e2-4b23-9e11-dbc624fb3b99.gif)

2022-01-05 16:26 UTC, ilivss commented
## Error state
![image](https://user-images.githubusercontent.com/6729273/148252713-e4535f56-beb1-4480-a422-43d6bcc31c6c.png)#140 

## Loading state
![loading-state](https://user-images.githubusercontent.com/6729273/148252781-53547120-3690-42ab-aee7-ba3f18e672ff.gif)

2022-01-10 08:52 UTC, mjqnsen approved these changes

2022-01-10 09:59 UTC, RubenEppink requested changes

2022-01-10 09:59 UTC, RubenEppink commented on wcag-tool/chrome-extension/src/components/common/ButtonWithDropdown.jsx
> +                  item.onClick()
klopt dit wel? nu voer je de onClick functie direct uit

2022-01-10 09:59 UTC, RubenEppink commented on wcag-tool/chrome-extension/src/hooks/editor.hooks.js
> +        setError('Cannot not analyse snapshot!')
```suggestion
        setError('Cannot analyse snapshot!')
```

2022-01-10 09:59 UTC, RubenEppink commented on wcag-tool/chrome-extension/src/hooks/editor.hooks.js
> +  useEffect(() => {
kan weg?

2022-01-10 09:59 UTC, RubenEppink commented on wcag-tool/package.json
> +  "license": "MIT",
ik wist niet dat wij open source waren :'( https://opensource.org/licenses/MIT

2022-01-11 08:27 UTC, RubenEppink approved these changes

2022-01-11 10:28 UTC, merged