Task/123 editor side by side with iframe
HANICA-DWA/sep2021-project-opossum pull request #151
Opened 2021-12-29 10:16 UTC by RubenEppink

heb ook een refactor gedaan van options form. herbruikbare toggle en tekst veld

fix #123
![sidebyside2](https://user-images.githubusercontent.com/47324044/147651731-480d01d8-2923-48a3-a4b4-3ebb30d5d653.gif)

2022-01-10 11:25 UTC, mjqnsen requested changes
Op de options pagina wanneer het username veld leeg is, dan zie ik dat het niet mogelijk is om te saven. Wellicht moet je ff aangeven dat de save knop niet werkt wanneer het username veld leeg is. Door een error validatie of door de knop disabled te maken.

2022-01-10 11:25 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/components/editor/App.jsx
> +  const [{}, { anySliderOpen }] = useSliders()
dus die empty pattern is nodig?

2022-01-10 11:25 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/hooks/awareness.hook.js
> +  console.log('name', name)
log kan wel weg toch?

2022-01-10 13:31 UTC, mjqnsen requested changes
LGTM, ik laat hem nog even open voor die andere bug met het iframe.

Daar ga ik binnenkort naar kijken wanneer ik tijd heb.

2022-01-10 13:47 UTC, ilivss commented on wcag-tool/chrome-extension/src/components/common/Icon.jsx
> +      viewBox={`0 0 ${viewBox} ${viewBox}`}
Lekkeer maaaaaan

2022-01-10 13:48 UTC, ilivss commented on wcag-tool/chrome-extension/src/components/editor/App.jsx
> +  const [{}, { anySliderOpen }] = useSliders()
Wat gebruikelijk is in javascript: _ als je een variabele niet gebruikt.

2022-01-10 14:17 UTC, ilivss approved these changes
:ok_hand:

2022-01-10 14:17 UTC, ilivss commented on wcag-tool/chrome-extension/src/components/options/OptionsForm.jsx
> +  const [options, setOptions] = useState({ username: '', sideBySide: false })
username zorgt voor bug :(

2022-01-13 13:44 UTC, mjqnsen approved these changes

2022-01-13 13:46 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/components/options/OptionsForm.jsx
> +        infoTitle="When activated enables the menu to be side-by-side with the page snapshot. Deactivate to have the menu slide over the page snapshot."
```suggestion
        infoTitle="When activated enables the menu to be side-by-side with the page snapshot. 
        Deactivate to have the menu slide over the page snapshot."
```

2022-01-13 14:25 UTC, ilivss approved these changes

2022-01-13 14:41 UTC, ilivss approved these changes

2022-01-13 15:04 UTC, merged