Task/146 overdracht feedback
HANICA-DWA/sep2021-project-opossum pull request #154
Opened 2022-01-10 09:30 UTC by RubenEppink

2022-01-10 13:36 UTC, mjqnsen approved these changes

2022-01-10 14:22 UTC, ilivss commented on wcag-tool/package.json
>  {
:ok_hand:

2022-01-10 14:23 UTC, RubenEppink commented on README.md
> +7. Make sure you database instance is running if you're using a local Mongo instance.
```suggestion
7. Make sure your database instance is running if you're using a local Mongo instance.
```

2022-01-10 14:23 UTC, ilivss commented on wcag-tool/chrome-extension/src/services/apiService.js
> +  baseQuery: fetchBaseQuery({ baseUrl: config.SERVER_URL }),
:ok_hand:

2022-01-10 14:24 UTC, RubenEppink commented on wcag-tool/chrome-extension/tests/unit/utils.index.test.js
> +      "Cannot read property 'charAt' of null"
```suggestion
      "Cannot read properties of null (reading 'charAt')"
```

2022-01-11 12:40 UTC, mjqnsen commented on README.md
> +> Run all integration tests for both front- and backend.
```suggestion
> Run all integration tests for backend.  
```

2022-01-11 12:42 UTC, mjqnsen requested changes

2022-01-11 12:42 UTC, mjqnsen commented on README.md
> +
```suggestion

> **npm run test:e2e**
> Run all e2e tests.
```

2022-01-11 12:52 UTC, mjqnsen commented on README.md
> +> **npm run lint**
```suggestion

> **npm run lint**
```

2022-01-11 13:03 UTC, mjqnsen approved these changes

2022-01-11 14:00 UTC, ilivss approved these changes
👌🏽

2022-01-11 14:02 UTC, merged