Prototype/multi language
HANICA-DWA/sep2021-project-opossum pull request #167
Opened 2022-01-13 10:35 UTC by RubenEppink

2022-01-13 14:04 UTC, mjqnsen requested changes
Ik heb in mijn PR nog strings toegevoegd. dus moet daar even op wachten.

mss kan copilot daarbij helpen haha

2022-01-13 14:05 UTC, mjqnsen requested changes
Full details translations mist.

2022-01-14 09:08 UTC, mjqnsen approved these changes

2022-01-14 09:08 UTC, ilivss approved these changes

2022-01-14 09:09 UTC, mjqnsen commented on wcag-tool/chrome-extension/public/assets/i18n/translations/en.json
> +  "SIDE_BY_SIDE_INFO": "When activated enables the sliding editor to be side-by-side with the snapshot.\nBy default the editor slides over the page.",
deze translation klopt niet meer.

2022-01-14 09:32 UTC, merged