Server indeling. Routing/testing/mongoose etc.
HANICA-DWA/sep2021-project-opossum pull request #41
Opened 2021-11-19 08:34 UTC by RubenEppink

2021-11-19 08:39 UTC, mjqnsen commented on wcag-tool/backend/src/mongoose/models/snapshot.js
> +      type: String,
Moest een timestamp niet last edited en creation date hebben?

2021-11-19 08:39 UTC, mjqnsen commented on wcag-tool/backend/src/mongoose/models/snapshot.js
> +  { timestamps: true }
Dit geeft creation date aan?

2021-11-19 08:59 UTC, RubenEppink commented on wcag-tool/backend/src/mongoose/models/snapshot.js
> +  { timestamps: true }
https://masteringjs.io/tutorials/mongoose/timestamps hier iets meer info

2021-11-19 09:20 UTC, mjqnsen commented on wcag-tool/backend/src/mongoose/models/snapshot.js
> +  { timestamps: true }
Ziek handig

2021-11-19 09:20 UTC, mjqnsen approved these changes
Handige oplossing met timestamps!

2021-11-19 09:27 UTC, ilivss requested changes
Noice! 👍🏽

2021-11-19 09:27 UTC, ilivss commented on wcag-tool/backend/src/mongoose/models/wcagRule.js
> +const mongoose = require('mongoose');
Ik zou geen mongoose map maken. Dat maakt het veel te concreet. Ik zou gewoon models gebruiken

2021-11-19 09:27 UTC, ilivss commented on wcag-tool/backend/src/middleware.js
> +const mongoose = require('mongoose');
Ik zou een middleware map maken en daarin alle middleware los definieren.

2021-11-19 09:27 UTC, ilivss commented on wcag-tool/backend/src/routers/snapshotRouter.js
> +require('../mongoose/models/snapshot');
Je kan namepaces aangeven met barrel files in elke map. Als je dan nog iets aanpast (weet alleen niet meer wat) in package.json zou je ook kunnen requiren met '@models/snapshot'

2021-11-19 09:27 UTC, ilivss commented on wcag-tool/backend/src/server.js
> +const mongoPort = 27017;
Ik zou poortnummers in een .env file zetten

2021-11-19 09:27 UTC, ilivss commented on wcag-tool/backend/src/server.js
> +    `mongodb://localhost:${mongoPort}/${dbName}`,
Deze url zou ik ook een .env file zetten

2021-11-19 09:55 UTC, mjqnsen requested changes
Je kan alvast Atlas Mongo db gebruiken.

2021-11-19 09:57 UTC, ilivss requested changes
👌🏽 👌🏽 👌🏽

2021-11-19 09:57 UTC, ilivss commented on wcag-tool/backend/src/middleware/getSnapshot.js
> +const mongoose = require('mongoose');
Kunnen we niet beter, zoals je zelf suggereerde, Joy gebruiken hiervoor?

2021-11-19 09:57 UTC, ilivss commented on wcag-tool/backend/src/models/snapshot.js
> +const annotation = new mongoose.Schema(
annotationSchema

2021-11-19 09:57 UTC, ilivss commented on wcag-tool/backend/src/models/snapshot.js
> +const snapshot = new mongoose.Schema(
snapshotSchema

2021-11-19 09:57 UTC, ilivss commented on wcag-tool/backend/src/routers/annotationRouter.js
> +require('../models/snapshot');
line 2 en 3 ff omdraaien :)

2021-11-19 10:08 UTC, ilivss requested changes

2021-11-19 10:08 UTC, ilivss commented on wcag-tool/backend/src/server.js
> +    console.log(`wcag-tool server started on port ${process.env.PORT}`);
draai deze even om met regel 27 en voeg een niet console.log toe met database connected of iets dergelijks.

2021-11-22 09:13 UTC, mjqnsen approved these changes
Als alle comments verwerkt zijn vind ik het prima.

2021-11-22 09:26 UTC, RubenEppink commented on wcag-tool/backend/src/routers/annotationRouter.js
> +require('../models/snapshot');
hoezo?

2021-11-22 13:31 UTC, ilivss approved these changes

2021-11-23 08:01 UTC, merged