Task 18 popup menu maken
HANICA-DWA/sep2021-project-opossum pull request #43
Opened 2021-11-23 10:31 UTC by StefanoudeLohuis

2021-11-23 14:11 UTC, RubenEppink requested changes

2021-11-23 14:11 UTC, RubenEppink commented on wcag-tool/chrome-extension/src/views/components/popup/navigationButtons.jsx
> +  const next = nextHook()
dus bijvoorbeeld usePrevious ipv previousHook

2021-11-23 15:31 UTC, mjqnsen commented
Vergeet niet een pr te linken aan een taak. door bijvoorbeeld in het commit message of beschrijving van pr naar een issue te refereren. Kan ook in instellingen van PR gelinkt worden.

2021-11-24 09:57 UTC, RubenEppink approved these changes

2021-11-24 10:05 UTC, mjqnsen commented
Waar is placeholder.txt voor? kan deze weg?

2021-11-24 10:18 UTC, mjqnsen commented
Ik denk dat je een onclick van een button ook zo moet noemen. Voor ons als developer is dat logischer wanneer we je Button component gebruiken

2021-11-24 10:20 UTC, mjqnsen requested changes

2021-11-24 10:20 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/css/font/Poppins/OFL.txt
> +PREAMBLE
Ik zie ook andere font files die niet gebruikt worden in styles.css. die moeten verwijderd worden.

2021-11-24 10:20 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/views/components/popup/snapshotBody.jsx
> +  if (snapshots.length === 0) return <div>{NoSnapshotsFound()}</div>
NoSnapshotsFound is een functie call, zou ik aanroepen als een component.

2021-11-24 10:20 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/views/components/common/Button.jsx
> +      }}
```suggestion
      onClick={onClick}
```

2021-11-24 10:20 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/views/components/common/Button.jsx
> +  const { name, classNames, action, isDisabled } = props
```suggestion
  const { name, classNames, onClick, isDisabled } = props
```

2021-11-24 10:20 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/views/components/popup/header.jsx
> +        action={createSnapshot}
```suggestion
        onClick={()=> createSnapshot()}
```

2021-11-24 10:20 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/views/components/popup/navigationButtons.jsx
> +            action={previous}
```suggestion
            onClick={()=> previous()}
```

2021-11-24 10:20 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/views/components/popup/navigationButtons.jsx
> +            action={next}
```suggestion
            onClick={()=> next()}
```

2021-11-24 10:20 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/views/components/popup/noSnapshotsFound.jsx
> +          action={createSnapshot}
change action to onlick

2021-11-24 10:20 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/views/components/popup/searchBar.jsx
> +        <Button action={filter} classNames="searchIcon mx-2 mr-2" />
change action to onclick

2021-11-24 10:20 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/views/components/common/Button.jsx
> +  action: PropTypes.func.isRequired,
change action to onClick

2021-11-24 11:22 UTC, mjqnsen approved these changes

2021-11-24 11:34 UTC, merged