xpath vs css spike
HANICA-DWA/sep2021-project-opossum pull request #44
Opened 2021-11-23 15:17 UTC by RubenEppink

2021-11-23 15:24 UTC, mjqnsen commented on documentatie/Spikes/CSS vs XPath/XPath vs CSS selector.md
> +Het probleem: Het programmatisch aanwijzen van specifieke elementen op een pagina (in het val van een 'snapshot' is de content statisch).
```suggestion
Het probleem: Het programmatisch aanwijzen van specifieke elementen op een pagina (in het geval van een 'snapshot' is de content statisch).
```

2021-11-23 15:30 UTC, mjqnsen requested changes
Vergeet niet een pr te linken aan een taak. door bijvoorbeeld in het commit message of beschrijving van pr naar een issue te refereren. Kan ook in instellingen van PR gelinkt worden.

2021-11-23 15:57 UTC, RubenEppink commented on documentatie/Spikes/CSS vs XPath/XPath vs CSS selector.md
> +## Conclusie
```suggestion
## Conclu
```

2021-11-24 08:11 UTC, mjqnsen approved these changes

2021-11-24 10:03 UTC, StefanoudeLohuis approved these changes
Ziet er goed uit!

2021-11-24 10:05 UTC, merged