Task 23 annotatie aanmaken
HANICA-DWA/sep2021-project-opossum pull request #61
Opened 2021-11-30 20:52 UTC by mjqnsen

2021-11-30 20:54 UTC, mjqnsen commented on wcag-tool/chrome-extension/package.json
> +    "@popperjs/core": "^2.11.0",
might be unused dep

2021-11-30 20:55 UTC, mjqnsen commented
Add forgotten tooltips

2021-12-01 10:35 UTC, StefanoudeLohuis commented on documentatie/Spikes/CSS vs XPath/css-selector-demo/src/App.js
> +      console.time('unique');
Moeten deze console.time er nog in staan?

2021-12-01 10:36 UTC, mjqnsen commented on wcag-tool/chrome-extension/package.json
> +    "@popperjs/core": "^2.11.0",
removed

2021-12-01 10:51 UTC, StefanoudeLohuis commented on wcag-tool/chrome-extension/src/views/components/common/NavigationButton.jsx
> +const DefaultButton = function ({
Naamgeving klopt niet? Knop bestand heet NavigationButton maar in de file wordt het 'DefaultButton' genoemd

2021-12-01 11:00 UTC, StefanoudeLohuis approved these changes
Dit dus voor de toekomst, dit zou een PR zijn met zo'n 2 uur review tijd. Ben er op een bepaald moment grotendeels doorheen geskipt

2021-12-01 11:41 UTC, ilivss commented
Het werkt niet bij mij :(
![Peek 2021-12-01 12-38](https://user-images.githubusercontent.com/6729273/144228356-413e05b1-e5d3-4bc4-987e-ca6b2b0dad29.gif)

en linter geeft heel veel errors :(

2021-12-01 11:43 UTC, ilivss requested changes
Het werkt niet bij mij:
* ![Peek 2021-12-01 12-38](https://user-images.githubusercontent.com/6729273/144228518-ce8ef9e7-33c3-4f12-b233-e4f184707fa4.gif)
 * Ik heb `npm i` gedaan.
Er zijn ook heel veel lint errors en warnings.

2021-12-01 12:44 UTC, ilivss approved these changes

2021-12-01 12:55 UTC, RubenEppink approved these changes

2021-12-01 14:18 UTC, merged