Task 24 annotatie openen om te bekijken client side
HANICA-DWA/sep2021-project-opossum pull request #72
Opened 2021-12-02 11:20 UTC by StefanoudeLohuis

2021-12-02 15:13 UTC, RubenEppink approved these changes

2021-12-02 16:08 UTC, mjqnsen commented
Ja er komen wat changes aan van me andere pr die wss een merge conflict gaat veroorzaken. dus moeten ff wachten

2021-12-02 16:09 UTC, mjqnsen requested changes

2021-12-02 16:09 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/views/components/editor/index.js
> +export * from './AnnotationDetailSlider'
Deze file moet niet meer in dev komen. ik raad aan om ff dev te pullen voordat je merged

2021-12-02 16:11 UTC, mjqnsen commented
De grootte van de icoontjes komen niet overeen met die van het create annotation scherm.

![image](https://user-images.githubusercontent.com/49095667/144459613-30e4e36d-b47a-4eaa-9359-e270bfdaa023.png)

2021-12-02 16:28 UTC, ilivss approved these changes

2021-12-03 10:59 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/components/editor/AnnotationDetailSlider.jsx
>            <button
deze commented code kan weg

2021-12-03 11:01 UTC, mjqnsen requested changes

2021-12-03 11:01 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/components/editor/AnnotationDetailSlider.jsx
>    setListSliderIsOpen,
```suggestion
```

2021-12-03 11:59 UTC, RubenEppink approved these changes

2021-12-03 12:03 UTC, mjqnsen approved these changes

2021-12-03 12:07 UTC, merged