Task/53 wcag selector on client
HANICA-DWA/sep2021-project-opossum pull request #73
Opened 2021-12-02 16:08 UTC by ilivss

Done

2021-12-02 16:37 UTC, mjqnsen approved these changes
glhf

2021-12-02 16:39 UTC, mjqnsen requested changes
glhf

2021-12-04 10:01 UTC, RubenEppink approved these changes

2021-12-04 10:03 UTC, ilivss commented
Alles werkt bitches

2021-12-04 15:38 UTC, mjqnsen commented
Wanneer je een annotatie edit en op cancel klikt gaat hij naar de annotatie list. Hij zou weer terug naar annotatie detail moeten gaan.

2021-12-04 15:43 UTC, mjqnsen commented
Wanneer je een annotatie aanmaakt en een element selecteert wordt de highlight na een click verwijder
![Animation](https://user-images.githubusercontent.com/49095667/144715599-8607bb20-b639-457c-b157-b3920f9d928d.gif)
d

2021-12-04 15:55 UTC, mjqnsen commented
Verkeerde knop bij het annotatie selecteren.
![4](https://user-images.githubusercontent.com/49095667/144716018-61d8ed1b-0735-478e-91f2-6addd6fb7646.gif)
.

2021-12-04 15:56 UTC, mjqnsen commented
Selector input veld lijkt niet echt op een selector veld.

2021-12-04 15:58 UTC, mjqnsen commented
Ik vind het bijwerken van het titel veld behaviour apart. hij komt pas als je in het input veld staat. Als dat niet beter kan moet je wellicht een klop toevoegen waarmee je het veld onclick mee kan invullen

2021-12-04 15:58 UTC, mjqnsen requested changes
Zie comments hierboven. naar de code zelf moet ik nog kijken.

2021-12-05 09:03 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/components/editor/OverlayButton.jsx
> +        hidden={!elementSelecorIsOpen}
```suggestion
        hidden={elementSelecorIsOpen}
```
ik gok dat dit de oplossing is. Deze knop moet weergeven worden wanneer hij wel open is.

2021-12-06 08:21 UTC, ilivss commented
> Wanneer je een annotatie edit en op cancel klikt gaat hij naar de annotatie list. Hij zou weer terug naar annotatie detail moeten gaan ![2](https://user-images.githubusercontent.com/49095667/144715683-b9d4711d-581d-45ba-98ae-26db681b6388.gif) .

Fixed.

2021-12-06 12:35 UTC, mjqnsen approved these changes

2021-12-06 12:35 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/components/editor/CreateAndEditAnnotationSlider.jsx
> +        closeEditor={closeEditor}
gaat deze regel goed?

2021-12-06 12:35 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/components/editor/AnnotationDetailSlider.jsx
> +              onClick={() => openCreateAndEditSlider()}
selected annotation hoeft niet meer mee gegeven worden?

2021-12-06 12:35 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/components/editor/CreateAndEditAnnotationSlider.jsx
> +  const closeEditor = selectedAnnotationId
ah ik zie dat deze functie is aangepast. netjes :)

2021-12-06 13:42 UTC, merged