Task 65 create annotation backend connection
HANICA-DWA/sep2021-project-opossum pull request #74
Opened 2021-12-02 18:33 UTC by RubenEppink

2021-12-02 18:53 UTC, ilivss requested changes
Mooi gedaan! :ok:

2021-12-02 18:53 UTC, ilivss commented on wcag-tool/backend/src/database.js
>  const mongoose = require('mongoose')
Nice

2021-12-02 18:53 UTC, ilivss commented on wcag-tool/chrome-extension/src/services/apiService.js
> +    getAnnotations: builder.query({
Nice

2021-12-02 18:53 UTC, ilivss commented on wcag-tool/chrome-extension/src/views/components/editor/AnnotationList.jsx
> +    <Annotation key={_id} title={title} description={description} selector={selector} />
Ik zou dit AnnotationListItem noemen, Annotatie vind ik te generiek.

2021-12-02 18:53 UTC, ilivss commented on wcag-tool/chrome-extension/src/views/components/editor/AnnotationListSlider.jsx
> +import { setSelectElement, unsetSelectedAnnotation } from '../../../services/annotationSlice'
Wat doet setSelectElement, gaat dat over html selector?
En wat doet unsetSelectedAnnotation? Kun je niet setSelectedAnnotation(undefined) doen?

2021-12-02 18:53 UTC, ilivss commented on wcag-tool/chrome-extension/src/views/components/editor/CreateAndEditAnnotationSlider.jsx
>    const isOpen = useSelector(selectorCreateSliderIsOpen)
als je `const { isOpen, selector } = useSelector(state => state.annotations)` gebruikt scheelt het 2 lines in dit bestand en 2 lines in `annotationSlice.js`

2021-12-02 18:53 UTC, ilivss commented on wcag-tool/chrome-extension/src/views/components/editor/CreateAndEditAnnotationSlider.jsx
> +                dispatch(unsetNewAnnotationSelector())
`setNewAnnotationSelector(undefined)`

2021-12-03 07:42 UTC, RubenEppink commented on wcag-tool/chrome-extension/src/views/components/editor/AnnotationListSlider.jsx
> +import { setSelectElement, unsetSelectedAnnotation } from '../../../services/annotationSlice'
ik heb dit niet geschreven. geen idee

2021-12-03 07:43 UTC, RubenEppink commented on wcag-tool/chrome-extension/src/views/components/editor/CreateAndEditAnnotationSlider.jsx
>    const isOpen = useSelector(selectorCreateSliderIsOpen)
niet relevant voor de PR

2021-12-03 07:43 UTC, RubenEppink commented on wcag-tool/chrome-extension/src/views/components/editor/CreateAndEditAnnotationSlider.jsx
> +                dispatch(unsetNewAnnotationSelector())
dat is wat unset doet

2021-12-03 07:45 UTC, RubenEppink commented on wcag-tool/chrome-extension/src/views/components/editor/AnnotationListSlider.jsx
> +import { setSelectElement, unsetSelectedAnnotation } from '../../../services/annotationSlice'
unset zet de waarde naar undefined

2021-12-03 08:03 UTC, ilivss approved these changes

2021-12-03 08:26 UTC, mjqnsen approved these changes

2021-12-03 08:27 UTC, merged