Task 90 richt text editor
HANICA-DWA/sep2021-project-opossum pull request #93
Opened 2021-12-08 16:24 UTC by RubenEppink

Dit is nog niet collaboratief. Alleen die speciale editor toegevoegd aan title en description. veel gezeik met formik en quill samen. Validatie moeten herschrijven. 

De velden zijn nog niet gestyled want dat lukt me niet door een bug

2021-12-09 08:59 UTC, ilivss commented on wcag-tool/chrome-extension/src/components/editor/AnnotationForm.jsx
>      description: selectedAnnotation?.description || '',
Bug: Wanneer er een tweede nieuwe annotatie wordt aangemaakt is de title value nog van de vorige gemaakte annotaties,

2021-12-09 09:38 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/components/editor/AnnotationForm.jsx
>      description: selectedAnnotation?.description || '',
Ook bij het aanmaken van een nieuwe en editen van een annotatie blijven de ingevoerde waardes staan.

2021-12-09 09:38 UTC, mjqnsen commented
Ik heb ook deze bug.
![5](https://user-images.githubusercontent.com/49095667/145371598-e1a67cb2-3223-405f-a72d-29eba2bc3b38.gif)

2021-12-09 09:40 UTC, mjqnsen requested changes
zie comments

2021-12-09 09:45 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/components/editor/RichTextEditor.jsx
> +    />
```suggestion
    <ReactQuill
      id={`${field.name}-editor`}
      modules={modules}
      value={field.value}
      placeholder={placeholder}
      onChange={(value) => setFieldValue(field.name, value)}
      ref={reactQuillRef}
      className="bg-white text-base font-normal"
    />
```

2021-12-09 09:47 UTC, mjqnsen commented
tooltip voor deze knop werkt niet meer 
![image](https://user-images.githubusercontent.com/49095667/145373055-15647438-ccea-4dde-98a1-4eff48cf67dc.png)

2021-12-13 10:08 UTC, ilivss requested changes
Problemen van voor het weekend netjes opgelost, nice! 👌🏽

2021-12-13 10:08 UTC, ilivss commented on wcag-tool/chrome-extension/src/components/editor/RichTextEditor.jsx
> +Quill.register('modules/cursors', QuillCursors, false)
Er is een rare bug: wanneer een andere gebruiker de editor verlaat, blijft zijn cursor online. Miss ff samen naar kijken? Was niet op de hoogte dat dit zo bleef
![image](https://user-images.githubusercontent.com/6729273/145791441-69b9b1a3-dcc8-43d7-b063-d16846c0d6b8.png)

2021-12-14 12:48 UTC, mjqnsen approved these changes

2021-12-14 12:49 UTC, mjqnsen commented
Alleen nog ff merge conflicts oplossen. Ik doe weer een goeie functionele check wanneer we bezig gaan met resource locking in sprint 3.

2021-12-20 08:34 UTC, ilivss approved these changes
:ok_hand:

2021-12-20 10:35 UTC, merged