Task 84 awareness frontend design voor alle collaborateurs
HANICA-DWA/sep2021-project-opossum pull request #94
Opened 2021-12-09 10:30 UTC by StefanoudeLohuis

2021-12-09 13:46 UTC, RubenEppink requested changes

2021-12-09 13:46 UTC, RubenEppink commented on wcag-tool/chrome-extension/src/components/common/Awareness.jsx
> +}
```suggestion
const firstLetterAndCapitalize = (str = '') => str.charAt(0).toUpperCase()

```

2021-12-09 13:46 UTC, RubenEppink commented on wcag-tool/chrome-extension/src/components/common/Awareness.jsx
> +      const names = [
Waarom definieer je die arrays in de useEffect? Kan ook boven het component toch?

2021-12-11 13:10 UTC, RubenEppink commented on wcag-tool/chrome-extension/src/components/common/Awareness.jsx
> +import React, { useState, useEffect } from 'react'
Awareness.jsx zit nu in de common map? hoort in editor

2021-12-11 13:12 UTC, RubenEppink commented on wcag-tool/chrome-extension/src/components/common/Awareness.jsx
> +      className={`flex flex-col absolute top-12 p-4 pr-8 pb-8 font-poppins ${position} ${invisible}`}
title van de <p> op deze div en opacity-40 en hover:opacity-100

2021-12-20 08:43 UTC, mjqnsen approved these changes

2021-12-20 12:47 UTC, ilivss approved these changes
Jehtog

2021-12-20 12:56 UTC, RubenEppink approved these changes

2021-12-20 12:57 UTC, merged