Task 67 client server koppelen snapshots opslaan
HANICA-DWA/sep2021-project-opossum pull request #95
Opened 2021-12-09 12:47 UTC by mjqnsen

2021-12-09 13:12 UTC, mjqnsen commented
Todo:
- [ ] Eerst snapshot persisten en daarna pas tab openen
- [ ] Errors handling laten zien in button
- [ ] Popup state opvragen vanuit background. wanneer er al een snapshot wordt aangemaakt of wanneer er een error is voorgekomen.

2021-12-13 11:14 UTC, ilivss requested changes
Mooi gedaan!

2021-12-13 11:14 UTC, ilivss commented on wcag-tool/chrome-extension/src/services/popupSlice.js
> +    setCreateSnapshotHeaderIsLoading: (state, { payload }) => {
Waarom niet 1 variabele voor `createSnapshotIsLoading`? Lijkt me too much om 2 variabele voor 2 verschillende knopjes te hebben.

2021-12-13 11:14 UTC, ilivss commented on wcag-tool/chrome-extension/src/services/snapshotSlice.js
> +  snapshotId: undefined,
Ik zou empty string doen

2021-12-13 11:14 UTC, ilivss commented on wcag-tool/chrome-extension/src/hooks/editor.hooks.js
> +export const useGetCurrentSnapshotId = () => {
Ik zou hier het volgende doen:
```js
const { snapshotId } = useSelector(state => state.snapshot)
return { snapshotId }
```

en de naam veranderen naar useSnapshots ofzo, er komt sws nog meer data in deze slice in de toekomst I guess

2021-12-13 11:14 UTC, ilivss commented on wcag-tool/chrome-extension/src/hooks/popup.hooks.js
> +import { useDispatch } from 'react-redux'
Nice

2021-12-13 12:46 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/hooks/annotation.hooks.js
> +import { useGetCurrentSnapshotId } from './editor.hooks'
and its gone

2021-12-13 12:57 UTC, mjqnsen commented on wcag-tool/chrome-extension/src/services/popupSlice.js
> +    setCreateSnapshotHeaderIsLoading: (state, { payload }) => {
komt omdat we twee knoppen hebben die anders van elkaar loaden. Ik zal button toevoegen aan de namen van de vars

2021-12-13 13:49 UTC, RubenEppink approved these changes

2021-12-13 14:00 UTC, ilivss approved these changes

2021-12-13 14:06 UTC, merged